
== bitcoin core

=== Two Different Size Limits:

* *MAX_SCRIPT_ELEMENT_SIZE* (in interpreter.cpp line 1882) - This is a consensus rule that limits individual stack elements to 520 bytes. This is what's currently blocking your SLH-DSA signature.
* *MAX_STANDARD_P2TSH_STACK_ITEM_SIZE* (in policy.h) - This is a policy rule that limits P2TSH stack items to 80 bytes (or 8000 bytes with your change) for standardness.

== P2TSH changes to rust-bitcoin

# 1. p2tsh module

The p2tsh branch of rust-bitcoin includes a new module: `p2tsh`.

Source code for this new module can be found [here](https://github.com/jbride/rust-bitcoin/blob/p2tsh/bitcoin/src/p2tsh/mod.rs).

Highlights of this _p2tsh_ module as follows:

## 1.1. p2tshBuilder

This is struct inherits from the rust-bitcoin _TaprootBuilder_.
It has an important modification in that it disables keypath spend.

Similar to its Taproot parent, p2tshBuilder provides functionality to add leaves to a TapTree.
One its TapTree has been fully populated with all leaves, an instance of _p2tshSpendInfo_ can be retrieved from p2tshBuilder.


```
pub struct p2tshBuilder {
    inner: TaprootBuilder
}

impl p2tshBuilder {

    /// Creates a new p2tsh builder.
    pub fn new() -> Self {
        Self {
            inner: TaprootBuilder::new()
        }
    }

    /// Adds a leaf to the p2tsh builder.
    pub fn add_leaf_with_ver(
        self,
        depth: u8,
        script: ScriptBuf,
        leaf_version: LeafVersion,
    ) -> Result<Self, p2tshError> {
        match self.inner.add_leaf_with_ver(depth, script, leaf_version) {
            Ok(builder) => Ok(Self { inner: builder }),
            Err(_) => Err(p2tshError::LeafAdditionError)
        }
    }

    /// Finalizes the p2tsh builder.
    pub fn finalize(self) -> Result<p2tshSpendInfo, p2tshError> {
        let node_info: NodeInfo = self.inner.try_into_node_info().unwrap();
        Ok(p2tshSpendInfo {
            merkle_root: Some(node_info.node_hash()),
            //script_map: self.inner.script_map().clone(),
        })
    }

    /// Converts the p2tsh builder into a Taproot builder.
    pub fn into_inner(self) -> TaprootBuilder {
        self.inner
    }
}
```

##  1.2. p2tshSpendInfo

Provides merkle_root of a completed p2tsh TapTree

```
/// A struct for p2tsh spend information.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct p2tshSpendInfo {

    /// The merkle root of the script path.
    pub merkle_root: Option<TapNodeHash>

}
```

## 1.3. p2tshScriptBuf

Allows for creation of a p2tsh scriptPubKey UTXO using only the merkle root of a script tree only.

```
/// A wrapper around ScriptBuf for p2tsh (Pay to Quantum Resistant Hash) scripts.
pub struct p2tshScriptBuf {
    inner: ScriptBuf
}

impl p2tshScriptBuf {
    /// Creates a new p2tsh script from a ScriptBuf.
    pub fn new(inner: ScriptBuf) -> Self {
        Self { inner }
    }
    
    /// Generates p2tsh scriptPubKey output
    /// Only accepts the merkle_root (of type TapNodeHash)
    /// since keypath spend is disabled in p2tsh
    pub fn new_p2tsh(merkle_root: TapNodeHash) -> Self {
        // https://github.com/cryptoquick/bips/blob/p2tsh/bip-0360.mediawiki#scriptpubkey
        let merkle_root_hash_bytes: [u8; 32] = merkle_root.to_byte_array();
        let script = Builder::new()
            .push_opcode(OP_PUSHNUM_3)

            // automatically pre-fixes with OP_PUSHBYTES_32 (as per size of hash)
            .push_slice(&merkle_root_hash_bytes)
            
            .into_script();
        p2tshScriptBuf::new(script)
    }

    /// Returns the script as a reference.
    pub fn as_script(&self) -> &Script {
        self.inner.as_script()
    }
}
```

## 1.4. p2tsh Control Block

Closely related to P2TR control block.
Difference being that _internal public key_ is not included.


```
/// A control block for p2tsh (Pay to Quantum Resistant Hash) script path spending.
/// This is a simplified version of Taproot's control block that excludes key-related fields.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct p2tshControlBlock {
    /// The version of the leaf.
    pub leaf_version: LeafVersion,
    /// The merkle branch of the leaf.
    pub merkle_branch: TaprootMerkleBranch,
}
```

# 2. Witness Program

New p2tsh related functions that allow for creation of a new V3 _witness program_ given a merkle_root only.

Found in bitcoin/src/blockdata/script/witness_program.rs

```
/// Creates a [`WitnessProgram`] from a 32 byte merkle root.
fn new_p2tsh(program: [u8; 32]) -> Self {
    WitnessProgram { version: WitnessVersion::V3, program: ArrayVec::from_slice(&program) }
}

/// Creates a pay to quantum resistant hash address from a merkle root.
pub fn p2tsh(merkle_root: Option<TapNodeHash>) -> Self {
    let merkle_root = merkle_root.unwrap();
    WitnessProgram::new_p2tsh(merkle_root.to_byte_array())
}
```

# 3. Address

New _p2tsh_ function that allows for creation of a new _p2tsh_ Address given a merkle_root only.

Found in bitcoin/src/address/mod.rs

```
/// Creates a pay to quantum resistant hash address from a merkle root.
pub fn p2tsh(merkle_root: Option<TapNodeHash>, hrp: impl Into<KnownHrp>) -> Address {
    let program = WitnessProgram::p2tsh(merkle_root);
    Address::from_witness_program(program, hrp)
}
```
