:scrollbar:
:data-uri:
:toc2:
:linkattrs:

= P2QRH End-to-End Tutorial

:numbered:

This tutorial is inspired from the link:https://learnmeabitcoin.com/technical/upgrades/taproot/#example-3-script-path-spend-signature[script-path-spend-signature] example of the _learnmeabitcoin_ tutorial for p2tr.

The tutorial is customized to create, fund and spend from a P2QRH UTXO (consisting of a single leaf taptree) to a P2WPKH address.

Execute in Bitcoin Core `regtest` mode.

== Pre-reqs

=== Bitcoin Core

TO-DO

=== Shell Environment

. *b-reg* command line alias:
+
Configure an alias to the `bitcoin-cli` command that connects to your customized bitcoin-core node running in `regtest` mode.
. *jq*: ensure json parsing utility is installed and available via your $PATH.
. *awk* : standard utility for all Linux distros (often packaged as `gawk`).

=== Bitcoin Core Wallet

This tutorial assumes that a bitcoin core wallet is available.
For example, the following would be sufficient:

-----
$ export W_NAME=regtest \
        && export WPASS=regtest

$ b-reg -named createwallet \
    wallet_name=$W_NAME \
    descriptors=true \
    passphrase="$WPASS" \
    load_on_startup=true
-----

== Fund P2QRH UTXO

. View (hard-coded) tapscript used in single leaf taptree:
+
-----
$ b-reg decodescript 206d4ddc0e47d2e8f82cbe2fc2d0d749e7bd3338112cecdc76d8f831ae6620dbe0ac | jq -r '.asm'

6d4ddc0e47d2e8f82cbe2fc2d0d749e7bd3338112cecdc76d8f831ae6620dbe0 OP_CHECKSIG
-----
+
NOTE:  Notice that this script commits to a Schnorr 32-byte x-only public key.

. Generate a P2QRH scripPubKey and address given a taptree as defined in link:https://learnmeabitcoin.com/technical/upgrades/taproot/#example-3-script-path-spend-signature[learnmeabitcoin tutorial] :
+
-----
$ export BITCOIN_NETWORK=regtest \
    && export BITCOIN_ADDRESS_INFO=$( cargo run --example p2qrh_construction ) \
    && echo $BITCOIN_ADDRESS_INFO | jq -r .
-----
+
NOTE:  In `regtest`, you can expect a P2QRH address that starts with: `bcrt1r` .
+
NOTE: In the context of P2QRH, the _tree_root_hex_ from the response is in reference to the _quantum_root_ used in this tutorial.

. Set some env vars (for use in later steps in this tutorial)  based on previous result:
+
-----
$ export QUANTUM_ROOT=$( echo $BITCOIN_ADDRESS_INFO | jq -r '.tree_root_hex' ) \
    && export FUNDING_SCRIPT_PUBKEY=$( echo $BITCOIN_ADDRESS_INFO | jq -r '.script_pubkey_hex' ) \
    && export P2QRH_ADDR=$( echo $BITCOIN_ADDRESS_INFO | jq -r '.bech32m_address' )
-----

. fund this P2QRH address with the coinbase reward of a newly generated block:
+
-----
$ export COINBASE_REWARD_TX_ID=$( b-reg -named generatetoaddress 1 $P2QRH_ADDR 1 | jq -r '.[]' ) \
    && echo $COINBASE_REWARD_TX_ID
-----
+
NOTE:  Sometimes Bitcoin Core does not immediately respond.  If so, wait a few seconds and try the above command again.

. view summary of all txs that have funded P2QRH address
+
-----
$ export P2QRH_DESC=$( b-reg getdescriptorinfo "addr($P2QRH_ADDR)" | jq -r '.descriptor' ) \
    && echo $P2QRH_DESC \
    && b-reg scantxoutset start '[{"desc": "'''$P2QRH_DESC'''"}]'
-----

. grab txid of first tx with unspent funds:
+
-----
$ export FUNDING_TX_ID=$( b-reg scantxoutset start '[{"desc": "'''$P2QRH_DESC'''"}]' | jq -r '.unspents[0].txid' ) \
    && echo $FUNDING_TX_ID
-----

. Set FUNDING_UTXO_INDEX env var (used later to correctly identify funding UTXO when generating the spending tx)
+
-----
$ export FUNDING_UTXO_INDEX=0
-----

. view details of funding UTXO to the P2QRH address:
+
-----
$ export FUNDING_UTXO=$( b-reg getrawtransaction $FUNDING_TX_ID 1 | jq -r '.vout['''$FUNDING_UTXO_INDEX''']' ) \
    && echo $FUNDING_UTXO | jq -r .
-----

== Spend P2QRH UTXO


. Determine value (in sats) of funding utxo:
+
-----
$ export FUNDING_UTXO_AMOUNT_SATS=$(echo $FUNDING_UTXO | jq -r '.value' | awk '{printf "%.0f", $1 * 100000000}') \
    && echo $FUNDING_UTXO_AMOUNT_SATS
-----

. Referencing the funding tx (via $FUNDING_TX_ID and $FUNDING_UTXO_INDEX), create the spending tx:
+
-----
$ export RAW_P2QRH_SPEND_TX=$( cargo run --example p2qrh_spend | jq -r '.tx_hex' ) \
    && echo $RAW_P2QRH_SPEND_TX
-----

. Inspect the spending tx:
+
-----
$ b-reg decoderawtransaction $RAW_P2QRH_SPEND_TX
-----

. Test standardness of the spending tx by sending to local mempool of p2qrh enabled Bitcoin Core:

.. Generate additional blocks.
+
This is necessary if you have only previously generated 1 block.
+
-----
$ b-reg -generate 110
-----
+
Otherwise, you may see an error from bitcoin core such as the following:
+
_bad-txns-premature-spend-of-coinbase, tried to spend coinbase at depth 1_

.. Execute:
+
-----
$ b-reg testmempoolaccept '["'''$RAW_P2QRH_SPEND_TX'''"]'
-----

. Submit tx:
+
-----
$ export P2QRH_SPENDING_TX_ID=$( b-reg sendrawtransaction $RAW_P2QRH_SPEND_TX ) \
    && echo $P2QRH_SPENDING_TX_ID
-----
+
NOTE:  Should return same tx id as was included in $RAW_P2QRH_SPEND_TX

== Mine P2QRH Spend TX

. View tx in mempool:
+
-----
$ b-reg getrawtransaction $P2QRH_SPENDING_TX_ID 1
-----
+
NOTE:  There will not yet be a field `blockhash` in the response.

. Mine 1 block:
+
-----
$ b-reg -generate 1
-----

. Obtain `blockhash` field of mined tx:
+
-----
$ export BLOCK_HASH=$( b-reg getrawtransaction $P2QRH_SPENDING_TX_ID 1 | jq -r '.blockhash' ) \
    && echo $BLOCK_HASH
-----

. View tx in block:
+
-----
$ b-reg getblock $BLOCK_HASH | jq -r .tx
-----

== TO-DO

=== Import P2QRH address into wallet

NOTE:  currently fails with:   "message": "Cannot import descriptor without private keys to a wallet with private keys enabled"

-----
$ b-reg -rpcwallet=$W_NAME walletpassphrase $WPASS 120
$ echo $P2QRH_ADDR
$ export P2QRH_DESC=$( b-reg getdescriptorinfo "addr($P2QRH_ADDR)" | jq -r '.descriptor' ) \
    && echo $P2QRH_DESC

# Set as non-active address (because can't generate subsequent p2qrh addresses yet)
$ b-reg importdescriptors '[{
  "desc": "'''$P2QRH_DESC'''",
  "timestamp": "now",
  "active": false,
  "label": "p2qrh"
}]'
-----
