[default]
extend-ignore-re = [
    # NOTE: use here for regex patterns
    "xpub.*",
    "xprv.*",
    "3.*", # address
    "5.*", # address
    "private_key .*",
    "privkey .*",
    "tt.*", # <tt> tags
    "code.*", # <code> tags
    "\\w*<sub>", # prefix for <sub> tags
    "OP_SUCCESSx|\\d+",
    "pay.*",
    "ser.*",
    "prefix.*",
    "value: .*",
]

[default.extend-words]
# NOTE: use here for false-positives
anc = "anc"
PSBT = "PSBT"
ser = "ser"
# Names
Atack = "Atack"
Meni = "Meni"
Ono = "Ono"

[files]
extend-exclude = [
    "/*/*.csv",
    "/*.d*",
    "/*/*.d*",
    "/*/*.go",
    "/*/*.json",
    "/*/*/*.json",
    "/*/*.mod",
    "/*/*.proto",
    "/*/*.py",
    "scripts",
    "/*/*.s*",
    "/*/*.t*",
]
