[project]
name = "secp256k1lab"
version = "1.0.0"
description = "An INSECURE implementation of the secp256k1 elliptic curve and related cryptographic schemes, intended for prototyping, experimentation and education"
readme = "README.md"
authors = [
    { name = "Pieter Wuille", email = "pieter@wuille.net" },
    { name = "Tim Ruffing", email = "me@real-or-random.org" },
    { name = "Jonas Nick", email = "jonasd.nick@gmail.com" },
    { name = "Sebastian Falbesoner", email = "sebastian.falbesoner@gmail.com" }
]
maintainers = [
    { name = "Tim Ruffing", email = "me@real-or-random.org" },
    { name = "Jonas Nick", email = "jonasd.nick@gmail.com" },
    { name = "Sebastian Falbesoner", email = "sebastian.falbesoner@gmail.com" }
]
requires-python = ">=3.9"
license = "MIT"
license-files = ["COPYING"]
keywords = ["secp256k1", "elliptic curves", "cryptography", "Bitcoin"]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "Intended Audience :: Education",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python",
  "Topic :: Security :: Cryptography",
]
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
