# Exclude vendored package.
extend-exclude = ["secp256k1lab/**"]

[lint]
extend-ignore = [
  # We catch "Exception" for good reasons.
  "BLE001",
  # Too many false positives (https://github.com/astral-sh/ruff/issues/7847).
  "B023",
  # We sort __all__ manually.
  "RUF022",
]
